### ISSUE TITLE
Tomb Raider II iOS Textures Mod

### ISSUE THREAD

**Issue by Milan978** [Arsunt/TR2Main#11]
Please add support for Tomb Raider II iOS Textures Mod.

**Comment by Arsunt** [comment]
Hello. This feature is in plans. When it is ready, I'll notify you in this issue.

**Comment by DonelBueno** [comment]
Any news on this?

Also, are there any other/better texture pack for TR2?

**Comment by Arsunt** [comment]
@DonelBueno the feature development is in progress

**Comment by rr-** [comment]
@Arsunt I was thinking about it for TR1M; maybe it'd make sense to replace `-gold` with `--mod=gold` and then we'd have easier management of vanilla/Gold version and get mod support out of the box?

For TR1M it's even more necessary because level names and files are hardcoded. I'd like to move them out of the code at some point, possibly to JSON.

**Comment by Arsunt** [comment]
@rr- no, mods are more specific cases that require more specific adjustment. -gold and -nogold are planned to use with the unmodified game, with no options there will be dialog with game selection. For mods there will be other scenarios, not related with gold/nogold mode.

About textures pack - texture pack is not a mod, it is an optional texture pack, that must be setup separately from mod (which consists from modded levels). Right now I'm implementing texture packs support for TR2Main.

**Comment by rr-** [comment]
I was thinking of such a solution because when a player wants to play mods, the Gold/Nogold setup doesn't make much sense to them – it only makes sense for an unmodded game, and assuming that they do have Gold purchased. Anyway I don't think I'll touch on TombUB anytime soon and I will look forward to your mod/gold setup to look for inspiration in TR1M. :)

**Comment by JOHN30011887** [comment]
i see that there is added external HD textures support but ow do we add a texture pack, is there a folder we need to make or something

**Comment by xXConcasXx** [comment]
> i see that there is added external HD textures support but how do we add a texture pack, is there a folder we need to make or something

Download textures here: https://drive.google.com/file/d/10MPs2bRu0-C6C-rrGCcrdmT1ZxiZnBWt/edit and copy textures folder inside game folder.

**Comment by MagikGimp** [comment]
Kristopher Lytwyn has updated those iOS textures to be even more HD! Check out his tweet here- [https://twitter.com/trfan94/status/1364646810271252480](https://twitter.com/trfan94/status/1364646810271252480).

**Comment by Arsunt** [comment]
Feature is implemented. I close the issue.
