### ISSUE TITLE
Game rotated my Intel graphics card 180 degrees 

### ISSUE THREAD

**Issue by noisecode3** [Arsunt/TR2Main#15]
I was playing normal on steam + steam gampad input and overlay with DS4Windows on windows 10.
screen went black for 1 second then everything was upside down :D
It happened at the map temple of xian
I was using developer build 20200902

**Comment by Arsunt** [comment]
Hey! This is your video adapter shortcut (probably Ctrl+Alt+Up or Ctrl+Alt+Down). Here is info how to disable it https://superuser.com/questions/279756

**Comment by Arsunt** [comment]
By the way You don't need DS4Windows. The latest TR2Main version has the native DS4 support, including Gamepad Lightbar health/air status. DS4Windows prevents the game from controlling lightbar colour

**Comment by noisecode3** [comment]
Thanks, what drivers are native for windows 10, ps4 dualshock? For this game I mean there is like a lot https://www.pcgamingwiki.com/wiki/Glossary:Controller#Windows
I like the light bar :D
if I just connect it with bt I get no input to game

**Comment by Arsunt** [comment]
You need no drivers on Windows 10. Just disable DS4Windows, run the game setup dialog, open "Controls" tab, make sure there is "Enable Joystick" is checked and "Sony Dualshock 4" controller is selected (not XInput Controller).

If you did not redefine keys in the game, you may need to redefine them using Custom Keyboard Layout (User Keys)

**Comment by noisecode3** [comment]
hmm. There is only 2 tabs with Default Keys and User keys. There is no enable joystick. Is it hidden somehow?

**Comment by Arsunt** [comment]
No. Setup dialog can be accessed via setup shortcut. Here is an instruction how to get it: https://steamcommunity.com/app/225300/discussions/0/41973820732243655/

**Comment by noisecode3** [comment]
Aha lol, thanks. its exact same named as in game :D

**Comment by Arsunt** [comment]
So does native Dualshock 4 support work for you?

**Comment by noisecode3** [comment]
well using it like that removed vibrating and thumbstick functionality, I found a the way to get steam recognize ps4 controller. but still I get best result from using xinput with thumbstick, I can turn almost all the way to the side without Lara stopping, I like that. It would be nice if I could make Lara walk with the thumbstick by turning it half of the full radius.

it could also just be that the problem is that I have to connect it using the original cable or a special Bluetooth adapter.

**Comment by Arsunt** [comment]
Well losing vibration is strange if your controller really displayed as "Sony Dualshock 4" in Setup dialog. If it's not, then it seems something wrong with native DS4 drivers on your system. But you can go on with DS4Windows if you don't care about Light Bar features.

About thumbstick functionality, right now there are two options: D-Pad or Left Stick (not both). It is planned to rework the game joystick controls, so it will be possible to use D-Pad and both sticks in the same time. As bonus there will be stick sensitivity for accurate turning, but not walking with half-radius, because walking is a very very special action in TR series, and accidental running instead of walking or vice versa can be fatal for Lara. Maybe just speed control for boat/snowmobile.

If you don't have any questions about Intel display rotation shortcuts, we can close this issue.

**Comment by noisecode3** [comment]
its not working without(thumbstick and vibration) using steam input and Xinput in game settings. I have properly uninstalled DS4Windows. I can live without Light Bar features. I don't have to play upside down anymore :D
