### ISSUE TITLE
Patch Italian version of TR2

### ISSUE THREAD

**Issue by xXConcasXx** [Arsunt/TR2Main#34]
Is it possible to patch Italian version of TR2? If I share italian tr2 executable can I have it patched?

**Comment by MagikGimp** [comment]
Ciao. Language specific files are nothing to do with the executable. According to [this post](https://www.tombraiderforums.com/showpost.php?p=8294946&postcount=84) you need the following files:

1. data/tombpc.dat - in-game text. 
2. data/main.sfx - sound effects, "A-ha!" and "No." phrases.
3. audio/cdaudio.mp3 - music tracks, cutscenes audio and assault course voice lines.
4. data/*.pcx or pix/*.pcx or pix/16x9/*.png - pictures with some text.

These should be in your original installation folder (copy the files to a new place for TR2Main) or come with the TR2Main download. Number 3 can be downloaded from the link at [https://www.tombraiderforums.com/showthread.php?t=139425](https://www.tombraiderforums.com/showthread.php?t=139425)

And a reminder to use the updated build of the .exe from [this post](https://www.tombraiderforums.com/showpost.php?p=8206492&postcount=7) rather than the one here on GitHub.
