### ISSUE TITLE
Checking Decompiled Function before PR

### ISSUE THREAD

**Issue by ghost** [Arsunt/TR2Main#8]
I decompiled Display_Inventory and i'm intending to decompile all function in inventory.cpp,
i need some help about item text that dont update when inventory moving, and fix some think like variable with "vXX" (replace XX with number) before i send you a PR ;) 

updated repo, new added branch develop: [TokyoSU/TR2Main/DevelopBranch](https://github.com/TokyoSU/TR2Main/tree/develop)

**Comment by Arsunt** [comment]
Thank you. I've take a fast look on your commit. There are many places that must be polished before Pull Request can be approved.
- IDA comments for variables should be removed, variables themselves should be optimized.
- Why to change the lines that are actually not changed? For example line 66 of ``vars.h``.
- Why did you delete some commented lines in ``demo.h``? They are important, because they point to not yet decompiled functions. 
- Why commit into master directly, not another branch? How will you synchronize your fork master with my master?
- Did you test how decompiled function work?

**Comment by ghost** [comment]
1) yes i just moved the variable directly, i will change it dont worry.
2) i not changed it, i'm actually surprised that notified any change on this lign :x 
probably tab or space ?
3) you delete it after set a "#define" and the address is there too, a define is there to signal that it's not decompiled but used no ? and i dont deleted any lign that are usefull like comment.
4) i'm not used of github sorry for it.
5) ? please explain it, i tested it and it worked, just the item text that wont updated when moving :(

i just view your reply as if you are angry to me, i'm using your database (very complete :))
and not tombraid, i'm new to decompile, the first project that use decompiled function is Tomb raider 3 aiming plugin: [Aiming Plugins Video](https://www.tombraiderforums.com/showthread.php?p=8083612#post8083612) that rewrite PistolHandler and ShotgunHandler, or newly LaraGun(), DrawLara(), AnimatePistols() etc... completly.
so if you say "Did you test how decompiled function work?" it just hurt me :'(

**Comment by Arsunt** [comment]
No, I don't want to hurt you. I'm not angry. It's just that in my main job I regularly do the review of the code of other developers (my colleagues), and I am very attentive to the details in pull requests. I asked just automatically, nothing personal. I'll checkout your code to find out what's wrong with text

**Comment by TokyoSU** [comment]
i updated the function:
- less variables.
- removed comment for variable.
- less code in loop.
- need to fix inventory-ingame that have move inversed (up-down)

**Comment by ghost** [comment]
i have a problem with InvOptionList,
the ring need value 4 but InvOptionList have max value 3, normally this value is:
```
#define InvOptionList               ARRAY_(0x00465608, INVENTORY_ITEM*, [5]) /* = {
    &InvPassportOption,
    &InvDetailOption,
    &InvControlOption,
    &InvSoundOption,
    &InvPhotoOption
}; */
```
but in the code only 3 item is showed (no detail item) !

**Comment by ghost** [comment]
Updated repo with last files, link in the first post ^.
- item text not updated for unknown reason.
- all item can do a 360° before activated :x

**Comment by ghost** [comment]
#deleted only inventory is uploaded in "/develop" branch

**Comment by Arsunt** [comment]
The priority is quality and perfect work, not total number of decompiled functions. The first version of decompilation should exactly match the original implementation, even if there are bugs made by the Core Design. All the bugs of the original game and new features will later be added by separate commits. If there are any problems, they must be solved before decompiling other functions. Otherwise, technical debt will grow, which then with much greater difficulty will have to be repaid. Preferably, independent tasks should be developed in separate branches, so that you can perform a pull-request for some tasks without blocking the implementation of others.

If you have stable decompilated and fully working function, I recommend to pull request it. In any case, I will have to refactor it first and check for compliance with the original code before I allow myself to merge the branch into the master.

**Comment by Arsunt** [comment]
> i have a problem with InvOptionList,
> the ring need value 4 but InvOptionList have max value 3, normally this value is:
> 
> ```
> #define InvOptionList               ARRAY_(0x00465608, INVENTORY_ITEM*, [5]) /* = {
>     &InvPassportOption,
>     &InvDetailOption,
>     &InvControlOption,
>     &InvSoundOption,
>     &InvPhotoOption
> }; */
> ```
> 
> but in the code only 3 item is showed (no detail item) !

Detail option is disabled on PC TR2. That's why.

> the typedef struct WEAPON_INFO dont exist in "types.h", i cant progress because
> &Weapons[] dont exist, in the database it's writed like this: "46 * weapon_type + 4610784" like in TR4.
> because it's a arrays ?.
> in TR4 i use: `#define Weapons(type) (46 * type + 4610784)`

I'll check when I get some free time. But obviously 46 is struct size. 4610784 is probably it's pointer. Create in IDA the dummy struct type of size 46 and try to identify its fields. Using such defines in the TR2Main is not the best idea.

**Comment by ghost** [comment]
My message upward not have been merged in "develop" repo for now,
- i just found 2 bug now (inventory.cpp), the first is that text is not updated (title and ingame), the other is that sometime the item with do a 360° before activated, and a 3 but i dont see if it's a bug, the item that are activated can be too much advanced and enter in the camera but i dont know it it's this :(.

for the PR, how you want to proceed exacly ?

> I'll check when I get some free time. But obviously 46 is struct size. 4610784 is probably it's pointer. Create in IDA the dummy struct type of size 46 and try to identify its fields. Using such defines in the TR2Main is not the best idea.

yea #define is not really safe but it work :x i do this only in TR4.
i'm not really aknowledge about dummy struct size, i will search some info about it, thanks for the tips :),

**Comment by TokyoSU** [comment]
I discovered the address of the Weapons Arrays: unk_465AE0.
just need to assign it in a struct[]

**Comment by ghost** [comment]
i updated the inventory.cpp and .h.
EDIT:
- Implemented InventorySprite in DrawInventoryItem (I dont know if it work or not).
- Fixed Key Inventory when KeyHole is used.

FINALLY !!
- Fixed text update.

Inventory now is fully working.

**Comment by ghost** [comment]
Ready for merge :)
PS: some variable of DrawRooms is added in vars.h now.

**Comment by Arsunt** [comment]
Hey! Congrats!

I'm back. Looking your PR

**Comment by Arsunt** [comment]
Merged! Thank you!
